active_master: "{{ cluster_name }}-master"
master_group_name: "{{ cluster_name + '_master' }}"
active_master_ip: "{{ hostvars[groups[cluster_name + '_master'][0]].ansible_default_ipv4.address}}"
active_master_public_ip: "{{ hostvars[groups[cluster_name + '_master'][0]].ansible_host }}"
active_master_inventory_hostname: "{{ hostvars[groups[cluster_name + '_master'][0]] }}"
