---
- import_tasks: install.yml
  when: not restart|default(False)
  tags:
  - install
  - elastic
  - elastic_install

- import_tasks: config.yml
  when: not restart|default(False)
  tags:
    - install
    - elastic
    - elastic_install

- import_tasks: start.yml
  when: not restart|default(False)
  tags:
    - start
    - elastic
    - elastic_start


- import_tasks: restart.yml
  when: restart|default(False)
  tags:
  - restart
  - elastic_restart
  - 
- set_fact:
    elastic_completed: true


#- import_tasks: config.yml
#  tags:
#    - install
#    - elastic
#    - elastic_install
#    - elastic_config

#
#- import_tasks: plugins.yml
#  tags:
#    - install
#    - elastic
#    - elastic_install
#    - elastic_plugins

#- import_tasks: start.yml
#  when: not restart|default(False)
#  tags:
#  - start
#  - elastic
#  - elastic_start
#  - set_fact:
#    elastic_completed: true

#- import_tasks: restart.yml
#  when: restart|default(False)
#  tags:
#  - restart
#  - elastic_restart
#- set_fact:
#    elastic_completed: true
