---
- ansible.builtin.import_tasks: install.yml
  when: not restart|default(False)
  tags:
  - install
  - cassandra
  - cassandra_install

- ansible.builtin.import_tasks: config.yml
  become: True
  tags:
  - install
  - cassandra
  - cassandra_install
  - cassandra_config

- ansible.builtin.import_tasks: start.yml
  become: True
  when: not restart|default(False)
  tags:
  - start
  - cassandra
  - cassandra_start

- ansible.builtin.import_tasks: restart.yml
  become: True
  when: restart|default(False)
  tags:
  - restart
  - cassandra_restart
- set_fact:
    cassandra_completed: true
