---

- name: update apt cache
  become: true
  apt: 
    update_cache: true
  when: not skip_packages | default(False)
  retries: 2

- name: install packages
  become: true
  package: 
    name:
      - dstat
      - rsync
    state: latest
  when: not skip_packages | default(False)

- name: install Java
  become: true
  package: 
    name: "{{ java_package }}" 
    state: present
  when: not skip_packages | default(False)



- name: disable net.ipv6.conf.all.disable_ipv6
  become: true
  sysctl: 
    name: net.ipv6.conf.all.disable_ipv6 
    value: "1" 
    state: present
  tags:
    - prepare

- name: disable net.ipv6.conf.lo.disable_ipv6
  become: true
  sysctl: 
    name: net.ipv6.conf.lo.disable_ipv6 
    value: "1" 
    state: present
  tags:
    - prepare

- name: increase hard file limits
  become: true
  pam_limits: 
    domain: "*" 
    limit_type: hard 
    limit_item: nofile 
    value: "1000000"
  tags:
    - prepare

- name: increase soft file limits
  become: true
  pam_limits: 
    domain: "*" 
    limit_type: soft 
    limit_item: nofile 
    value: "1000000"

- name: create hadoop group
  tags: [prepare]
  ansible.builtin.group:
    name: hadoop
    state: present

- name: create hadoop user
  tags: [prepare]
  ansible.builtin.user:
    name: "{{ hadoop_user }}"
    shell: /bin/bash
    comment: Hadoop user
    group: hadoop