---

- import_tasks: prepare.yml
  when: not skip_install|default(False)

- name: setup toree
  become: True
  shell: jupyter toree install
  when: not skip_install|default(False)
  tags:
  - install
  - jupyter_install

- name: create config
  shell: jupyter notebook --generate-config -y
  when: not skip_install|default(False)
  become: false
  tags:
  - install
  - jupyter_install

- name: change jupyter_notebook_config.py

  lineinfile:
    dest=/home/{{ hadoop_user }}/.jupyter/jupyter_notebook_config.py
    state=present insertafter=EOF
    line="c.NotebookApp.ip = '0.0.0.0'"
    create=true
  tags:
  - install
  - jupyter_install

- name: copy toree kernel config
  become: True
  file: path=/usr/local/share/jupyter/kernels/toree_python{{python_version}} state=directory
  tags:
  - install
  - jupyter_install
- name: copy toree kernel config
  become: True
  template: src=toree_kernel.json.j2 dest=/usr/local/share/jupyter/kernels/toree_python{{python_version}}/kernel.json
  tags:
  - install
  - jupyter_install

- name: download scala
  shell: wget http://www.scala-lang.org/files/archive/scala-2.10.4.deb
  when: not skip_install|default(False)
  tags:
  - install
  - jupyter_install

- name: get dependencies
  package: name=libjansi-java state=present
  become: True
  tags:
  - install
  - jupyter_install

- name: do magic
  become: True
  shell: apt-get update
  when: not skip_install|default(False)
  tags:
  - install
  - jupyter_install

- name: install scala
  become: True
  shell: apt-get install -y scala
  when: not skip_install|default(False)
  tags:
  - install
  - jupyter_install

- import_tasks: service.yml
  become: True
  become_user: root
  when: install_as_service

- debug: msg="jupyter install finished on {{ hostvars[inventory_hostname].ansible_ssh_host }} (python_version={{ python_version }})"
