---

- name: acknowledge existing servers
  openstack.cloud.server_info:
  register: instances

- name: debug
  set_fact: 
    alive_servers: "{{ alive_servers | default([]) + [ item.name ] }}"
  when: item.metadata['group'] is defined and (cluster_name + '_master' == item['metadata']['group'] or cluster_name + '_slaves' == item['metadata']['group'] or cluster_name + '_runner' == item['metadata']['group'])
  with_items: "{{ instances.servers }}"
  no_log: True

- name: The following instances will be destroyed now
  debug: 
    var: alive_servers

- name: destroy cluster instances
  openstack.cloud.server:
    state: absent
    name: "{{ item }}"
  with_items: "{{ alive_servers }}"
  retries: 3

- name: destroy security group
  include_tasks: destroy_security_group.yml
