---

- name: get Hadoop distro checksum
  local_action: 
    module: get_url 
    url: "{{ hadoop_checksum_url }}"
    dest: files/
  become: false
  when: "hadoop_version != 'cdh4'"
  tags:
  - install
  - spark_install

- name: extract Hadoop checksum from file
  set_fact: 
    hadoop_sha512: "{{ lookup('file', hadoop_arch_checksum) | regex_replace('.*SHA512.+ ', '' ) |  replace(' ', '') }}"
  when: "hadoop_version != 'cdh4'"
  tags:
  - install
  - spark_install

- name: Hadoop checksum
  debug: var=hadoop_sha512

- name: get Spark distro checksum
  local_action: 
    module: get_url 
    url: "{{ spark_checksum_url }}" 
    dest: files/
  become: false
  tags:
  - install
  - spark_install

- name: extract Spark distro checksum from file
  set_fact: 
    spark_sha512: "{{ lookup('file', spark_arch_checksum) | regex_replace('  spark.*', '') |  replace(' ', '') }}"
  tags:
  - install
  - spark_install

- name: Spark checksum
  debug: var=spark_sha512

- import_tasks: tasks/prepare_spark.yml
  become: True
  become_user: root
  when: spark_common_completed is undefined
  tags:
  - install
  - spark_install

- import_tasks: detect_java_home.yml
  when: spark_common_completed is undefined

- import_tasks: as_root.yml
  become: True
  become_user: root
  when: spark_common_completed is undefined and not skip_spark_setup | default(False)
  tags:
  - install
  - spark_install

- set_fact:
    spark_common_completed: true
