---

- hosts: localhost
  gather_facts: false
  tasks:
    - name: Register master facts
      openstack.cloud.server_info:
        filters:
          metadata:
            group: "{{ cluster_name }}_master"
      register: master
    - debug: msg="{{ master.servers[0].access_ipv4 }}"
