---

- hosts: localhost
  gather_facts: no
  tasks:
    - name: Register master facts
      openstack.cloud.server_info:
        filters:
          metadata:
            group: "{{ cluster_name }}_{{ extended_role }}"
      no_log: True
    - debug: msg="{{ openstack_servers[0].interface_ip if openstack_servers[0].interface_ip != '' else openstack_servers[0].private_v4 }}"
