---

- name: Install necessary packages
  become: True
  apt: name={{ item }} state=present
  with_items:
    - curl
    - python-software-properties

- name: Add nodejs LTS repo
  become: True
  shell: "curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash - "

- debug: var=python_version
- block:
  - name: install packages
    become: True
    apt: name={{ item }} state=present
    with_items:
      - nodejs

  - become: True
    npm:
      global: true
      name: configurable-http-proxy

  - name: install pip packages
    become: True
    pip: name={{ item }} state=present executable=pip{{ python_version }}
    with_items:
      - jupyterhub

  - copy: src=jupyterhub_config.py dest=/home/{{ hadoop_user }}
  tags:
  - install
  - jupyterhub_install


